[BYTEMAN-428] MethodExpression#getPathCount quickfix
bytemanproject/byteman pull request #94
Opened 2023-03-02 20:10 UTC by tadamski

https://issues.redhat.com/browse/BYTEMAN-428

2023-03-03 11:53 UTC, adinn commented
Hi Tomasz. Yes, there is definitely a bug here and it appears to have been there since 2009! Well done for finding it.

2023-03-03 13:07 UTC, adinn requested changes

2023-03-03 13:41 UTC, tadamski commented on agent/src/main/java/org/jboss/byteman/rule/expression/MethodExpression.java
>                  }
@adinn Thanks for the explanation. tbh all the corner cases that this method takes care of weren't obvious for me  when I was trying to think of the fix. I have update the PR according to your suggestion.

2023-03-06 09:16 UTC, merged

2023-03-06 09:17 UTC, adinn commented
Fix for main branch -- still needs backporting to 3.X branch

2023-03-06 12:28 UTC, adinn commented
Fix also pushed to 3.X branch